#!/bin/sh
### BEGIN INIT INFO
# Provides:          CheckPass
# Required-Start:    $local_fs
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Check htaccess passwords
### END INIT INFO

# Set the USER variable to the name of the user to start tightvncserver under

eval cd /home/pi/Documents/Immrama

sleep 20
./conductor_password.py /var/www/html/conductor/config.ini --check

exit 0
